#ifndef ERRORINFO_H
#define ERRORINFO_H

namespace ErrorInfos {
    enum Type
    {
        NO_ERROR,
        PAYMENT_REJECTED_OFFLINE,
        PAYMENT_REJECTED_BLOCKED,
        PAYMENT_REJECTED_CONCURRENTTX,
        PAYMENT_ID_MISMATCH,
        PAYMENT_UNKNOWN_ID,
        PAYMENT_EXPIRED,
        PAYMENT_REJECTED_CONNECTOR_RESERVED,
        FAULT_DETECTED,
        CHARGE_STOP_FAIL,
        CHARGE_START_FAIL,
        PLUG_NOT_CONNECTED_PROPERLY,
        AUTHORIZATION_TIMEOUT,
        UNAVAILABLE_DETECTED,
        LOCK_FAIL,
        CHARGE_START_CONDITION_FAIL,
        CHARGE_START_FAIL_ENERGY_READ_ERROR,
        CONNECTOR_INITIALIZING,
        LID_ERROR,
        COUNT
    };
};
typedef ErrorInfos::Type ErrorInfo;

#endif // ERRORINFO_H
