#ifndef FIRMWAREUPDATESTATE_H
#define FIRMWAREUPDATESTATE_H

namespace FirmwareUpdateState {
enum FirmwareUpdateState{
    UNKNOWN_STATE,
    INCOMPLETE,
    TRANSFERRING,
    TRANSFER_COMPLETED,
    INSTALLING,
    INSTALLATION_FAILED,
    INSTALLATION_SUCCESSFUL,
    REBOOTING,
    COUNT
};
}

#endif // FIRMWAREUPDATESTATE_H
